language: python
python:
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install coverage
  - pip install coveralls
script:
  - python -m unittest discover -v tests/
  - coverage run main.py A+B
  - coveralls
